export enum ERoutes{
    login = 'login',
    register = 'register',
    plans = 'plans',
    forgotPassword = 'forgot-password',
    welcome = 'welcome',
    aboutUs = 'aboutUs',
    services = 'services',
    contact = 'contact',
    home = 'home',
    postRequest = 'deliver-request',
    postTrip = 'add-trip',
    searchResult = 'search',
    userReviews = 'user-reviews',
    deals = 'deals',
}