name: CI -> Deploy to My website
on:
  push:
    branches: [ dev ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Here is the deployment action
      - name: Upload from public_html via FTP
        uses: airvzxf/ftp-deployment-action@latest
        with:
          server: ${{secrets.SERVER_ADDRESS}}
          user: ${{secrets.SERVER_USERNAME}}
          password: ${{secrets.SERVER_PASSWORD}}
          remote_dir: ${{secrets.SERVER_DIR}}
          # local_dir: "./public_html/dev.lokinter"